DROP TABLE IF EXISTS `yuoshi_user_task_content_quest_solution_answers`;
DROP TABLE IF EXISTS `yuoshi_user_task_content_quest_solutions`;
DROP TABLE IF EXISTS `yuoshi_user_task_content_solutions`;
DROP TABLE IF EXISTS `yuoshi_user_task_solutions`;
DROP TABLE IF EXISTS `yuoshi_task_content_quest_answers`;
DROP TABLE IF EXISTS `yuoshi_task_content_quests`;
DROP TABLE IF EXISTS `yuoshi_task_contents`;
DROP TABLE IF EXISTS `yuoshi_tasks`;
DROP TABLE IF EXISTS `yuoshi_packages`;
